export const MockData = [
  { id: 1, name: "Lorem ipsum", percent: "10%", thing: "Arms" },
  { id: 2, name: "Lorem ipsum", percent: "20%", thing: "Horse" },
  { id: 3, name: "Lorem ipsum", percent: "30%", thing: "playstation" },
  { id: 4, name: "Lorem ipsum", percent: "40%", thing: "Pc" },
  { id: 5, name: "Lorem ipsum", percent: "50%", thing: "smartphone" },
  { id: 6, name: "Lorem ipsum", percent: "60%", thing: "Printer" },
  { id: 7, name: "Lorem ipsum", percent: "70%", thing: "Bazooka" },
  { id: 8, name: "Lorem ipsum", percent: "80%", thing: "Rpg" },
  { id: 9, name: "Lorem ipsum", percent: "90%", thing: "LightSaber" },
  { id: 10, name: "Lorem ipsum", percent: "100%", thing: "Force" },
  { id: 11, name: "Lorem ipsum", percent: "5%", thing: "Sith" },
  { id: 12, name: "Lorem ipsum", percent: "15%", thing: "Jedi" },
  { id: 13, name: "Lorem ipsum", percent: "25%", thing: "Cinema" },
  { id: 14, name: "Lorem ipsum", percent: "35%", thing: "Doctor" },
  { id: 15, name: "Lorem ipsum", percent: "45%", thing: "Airplane" },
  { id: 16, name: "Lorem ipsum", percent: "55%", thing: "Vent" },
  { id: 17, name: "Lorem ipsum", percent: "65%", thing: "Glass" },
  { id: 18, name: "Lorem ipsum", percent: "75%", thing: "Cup" },
];
